#用户表
CREATE TABLE IF NOT EXISTS `fmq_user`(
       `id` INT UNSIGNED AUTO_INCREMENT,
       `userName` VARCHAR(100) NOT NULL,
       `passWord` VARCHAR(40) NOT NULL,
       `create_date` DATE,
       PRIMARY KEY ( `id` )
     )ENGINE=InnoDB DEFAULT CHARSET=utf8;
     
INSERT INTO fmq_user(user_Name,pass_Word) VALUES ('1','123');



 
--权限系统的5张表
--角色资源关联 岗位表

CREATE TABLE IF NOT EXISTS `ADMIN_ROLE_RESOURCE`(
       `ID` INT UNSIGNED AUTO_INCREMENT,
       `ROLE_ID` VARCHAR(40) NOT NULL,
       `RESOURCE_ID` VARCHAR(40) ,
       `IS_VALIDITY` CHAR(1) ,
       `CREATED_BY` VARCHAR(60) NOT NULL,
       `CREATED_DATE` date NOT NULL,
       `UPDATED_BY` VARCHAR(60) NOT NULL,
       `UPDATED_DATE` date NOT NULL,
       PRIMARY KEY ( `ID` )
     )ENGINE=InnoDB DEFAULT CHARSET=utf8;

--查看表结构
desc ADMIN_ROLE_RESOURCE;

--用户权限表
CREATE TABLE IF NOT EXISTS `ADMIN_USER_ROLE`(
       `ID` INT UNSIGNED AUTO_INCREMENT,
       `USER_ID` VARCHAR(40) NOT NULL,
       `ROLE_ID` VARCHAR(40) ,
       `IS_VALIDITY` CHAR(1) ,
       `CREATED_BY` VARCHAR(60) NOT NULL,
       `CREATED_DATE` date NOT NULL,
       `UPDATED_BY` VARCHAR(60) NOT NULL,
       `UPDATED_DATE` date NOT NULL,
       PRIMARY KEY ( `ID` )
     )ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
desc ADMIN_USER_ROLE;

--用户
CREATE TABLE IF NOT EXISTS `ADMIN_USERS`(
       `ID` INT UNSIGNED AUTO_INCREMENT,
       `USERNAME` VARCHAR(50) NOT NULL,
       `PASSWORD` VARCHAR(120) ,
       `IS_VALIDITY` CHAR(1) ,
       `USER_CODE` VARCHAR(50) ,
       `MOBILE` VARCHAR(20) ,
       `DEPT_NAME` VARCHAR(100) ,
       `LAST_NAME` VARCHAR(100) ,
       `email` VARCHAR(100) ,
       `CREATED_BY` VARCHAR(60) NOT NULL,
       `CREATED_DATE` date NOT NULL,
       `UPDATED_BY` VARCHAR(60) NOT NULL,
       `UPDATED_DATE` date NOT NULL,
       PRIMARY KEY ( `ID` )
     )ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
desc ADMIN_USERS;



--权限表
CREATE TABLE IF NOT EXISTS `ADMIN_ROLE`(
       `ID` INT UNSIGNED AUTO_INCREMENT,
       `ROLE_NAME` VARCHAR(50) NOT NULL,
       `ROLE_DESC` VARCHAR(255) ,
       `IS_VALIDITY` CHAR(1),
       `CREATED_BY` VARCHAR(60) NOT NULL,
       `CREATED_DATE` date NOT NULL,
       `UPDATED_BY` VARCHAR(60) NOT NULL,
       `UPDATED_DATE` date NOT NULL,
       PRIMARY KEY ( `ID` )
     )ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
desc ADMIN_ROLE;


--权限表
CREATE TABLE IF NOT EXISTS `ADMIN_RESOURCE`(
       `ID` INT UNSIGNED AUTO_INCREMENT,
       `RESOURCE_NAME` VARCHAR(255) NOT NULL,
       `RESOURCE_CODE` VARCHAR(50) ,
       `RESOURCE_TYPE` CHAR(1),
       `RESOURCE_URL` VARCHAR(2000) ,
       `RESOURCE_DESC` VARCHAR(250) ,
       `PARENT_ID` VARCHAR(50) ,
       `IS_VALIDITY` CHAR(1),
       `PAGE_URL` VARCHAR(255) ,
       `SORT` VARCHAR(50) ,
       `CREATED_BY` VARCHAR(60) NOT NULL,
       `CREATED_DATE` date NOT NULL,
       `UPDATED_BY` VARCHAR(60) NOT NULL,
       `UPDATED_DATE` date NOT NULL,
       PRIMARY KEY ( `ID` )
     )ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
desc ADMIN_RESOURCE;

show tables;

