server:
  port: 8081
  context-path: /
  session: 
    timeout: 10
  tomcat:
    uri-encoding: UTF-8 
    
spring:
  datasource: 
     url: jdbc:mysql://127.0.0.1:3306/test
     driver-class-name: com.mysql.jdbc.Driver
     username: root
     password: root
     max-idle: 10
     max-wait: 10000
     min-idle: 5
     initial-size: 5

logging:
  file: log.log
  level:
    root: WARN
    org: 
      springframework: 
        web: DEBUG
    com:
      fmq:
        common: INFO
             
             
             